// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TapDoc_Mobile_App_Backend.Models;

#nullable disable

namespace TapDoc_Mobile_App_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250222125802_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentID"));

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.AppointmentDetails", b =>
                {
                    b.Property<int>("AppointmentDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentDetailsID"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppointmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AppointmentFee")
                        .HasColumnType("float");

                    b.Property<int>("AppointmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfSlots")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("PaymentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentDetailsID");

                    b.HasIndex("AppointmentID")
                        .IsUnique();

                    b.ToTable("AppointmentsDetails");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.AvailabilityDetails", b =>
                {
                    b.Property<int>("AvailabilityDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityDetailsID"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AvailabilityDetailsID");

                    b.ToTable("AvailabilityDetails");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.DoctorCategories", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("DoctorCategories");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.DoctorDetails", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppointmentDetailsID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DoctorFee")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalExperience")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorID");

                    b.HasIndex("AppointmentDetailsID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("DoctorDetails");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.DoctorRatings", b =>
                {
                    b.Property<int>("DoctorRatingsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorRatingsID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DoctorRatingsID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("DoctorRatings");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.EmergencyContacts", b =>
                {
                    b.Property<int>("EmergencyContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmergencyContactID"));

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EmergencyContactID");

                    b.ToTable("EmergencyContacts");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.EmergencyServices", b =>
                {
                    b.Property<int>("EmergencyServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmergencyServiceID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EmergencyServiceID");

                    b.ToTable("EmergencyServices");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.LabRecordAnalysis", b =>
                {
                    b.Property<int>("LabRecordAnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabRecordAnalysisId"));

                    b.Property<int>("LabRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LabRecordAnalysisId");

                    b.HasIndex("LabRecordId");

                    b.ToTable("LabRecordAnalysis");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.LabRecords", b =>
                {
                    b.Property<int>("LabRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabRecordID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabRecordUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LabRecordID");

                    b.HasIndex("PatientID");

                    b.HasIndex("RecordID");

                    b.ToTable("LabRecords");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.Localizations", b =>
                {
                    b.Property<int>("LocalizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalizationID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PrimaryKey")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocalizationID");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.PatientDetails", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderTypeID")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<int>("HeightUnitID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PatientImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("WeightUnitID")
                        .HasColumnType("int");

                    b.HasKey("PatientID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("PatientDetails");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.Payments", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<double>("PaymentAmount")
                        .HasColumnType("float");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStripeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.PrescriptionDetailTimings", b =>
                {
                    b.Property<int>("PrescriptionDetailTimingsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionDetailTimingsID"));

                    b.Property<int>("FrequencyID")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionDetailID")
                        .HasColumnType("int");

                    b.Property<int>("ReminderOffsetMinutes")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionDetailTimingsID");

                    b.HasIndex("PrescriptionDetailID");

                    b.ToTable("PrescriptionDetailTimings");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.PrescriptionDetails", b =>
                {
                    b.Property<int>("PrescriptionDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionDetailID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrescriptionRecordID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isReminderEnabled")
                        .HasColumnType("bit");

                    b.HasKey("PrescriptionDetailID");

                    b.HasIndex("PrescriptionRecordID");

                    b.ToTable("PrescriptionDetails");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.PrescriptionRecords", b =>
                {
                    b.Property<int>("PrescriptionRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionRecordID"));

                    b.Property<int>("AppointmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("PrescriptionRecordUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PrescriptionRecordID");

                    b.HasIndex("AppointmentID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.HasIndex("RecordID");

                    b.ToTable("PrescriptionRecords");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.Records", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.HasKey("RecordID");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.Appointment", b =>
                {
                    b.HasOne("TapDoc_Mobile_App_Backend.Models.DoctorDetails", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TapDoc_Mobile_App_Backend.Models.PatientDetails", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.AppointmentDetails", b =>
                {
                    b.HasOne("TapDoc_Mobile_App_Backend.Models.Appointment", null)
                        .WithOne("AppointmentDetails")
                        .HasForeignKey("TapDoc_Mobile_App_Backend.Models.AppointmentDetails", "AppointmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.DoctorDetails", b =>
                {
                    b.HasOne("TapDoc_Mobile_App_Backend.Models.AppointmentDetails", null)
                        .WithMany("Doctors")
                        .HasForeignKey("AppointmentDetailsID");

                    b.HasOne("TapDoc_Mobile_App_Backend.Models.DoctorCategories", "DoctorCategories")
                        .WithMany("DoctorDetails")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TapDoc_Mobile_App_Backend.Models.Users", "Users")
                        .WithOne("DoctorDetails")
                        .HasForeignKey("TapDoc_Mobile_App_Backend.Models.DoctorDetails", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorCategories");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.DoctorRatings", b =>
                {
                    b.HasOne("TapDoc_Mobile_App_Backend.Models.DoctorDetails", "DoctorDetails")
                        .WithMany("DoctorRatings")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TapDoc_Mobile_App_Backend.Models.PatientDetails", "PatientDetails")
                        .WithMany("DoctorRatings")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorDetails");

                    b.Navigation("PatientDetails");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.LabRecordAnalysis", b =>
                {
                    b.HasOne("TapDoc_Mobile_App_Backend.Models.LabRecords", "LabRecords")
                        .WithMany()
                        .HasForeignKey("LabRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabRecords");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.LabRecords", b =>
                {
                    b.HasOne("TapDoc_Mobile_App_Backend.Models.PatientDetails", "PatientDetails")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TapDoc_Mobile_App_Backend.Models.Records", "Records")
                        .WithMany()
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientDetails");

                    b.Navigation("Records");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.PatientDetails", b =>
                {
                    b.HasOne("TapDoc_Mobile_App_Backend.Models.Users", "User")
                        .WithOne("PatientDetails")
                        .HasForeignKey("TapDoc_Mobile_App_Backend.Models.PatientDetails", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.PrescriptionDetailTimings", b =>
                {
                    b.HasOne("TapDoc_Mobile_App_Backend.Models.PrescriptionDetails", "PrescriptionDetails")
                        .WithMany("PrescriptionDetailTimings")
                        .HasForeignKey("PrescriptionDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrescriptionDetails");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.PrescriptionDetails", b =>
                {
                    b.HasOne("TapDoc_Mobile_App_Backend.Models.PrescriptionRecords", "PrescriptionRecords")
                        .WithMany()
                        .HasForeignKey("PrescriptionRecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrescriptionRecords");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.PrescriptionRecords", b =>
                {
                    b.HasOne("TapDoc_Mobile_App_Backend.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TapDoc_Mobile_App_Backend.Models.DoctorDetails", "DoctorDetails")
                        .WithMany()
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TapDoc_Mobile_App_Backend.Models.PatientDetails", "PatientDetails")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TapDoc_Mobile_App_Backend.Models.Records", "Records")
                        .WithMany()
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("DoctorDetails");

                    b.Navigation("PatientDetails");

                    b.Navigation("Records");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentDetails");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.AppointmentDetails", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.DoctorCategories", b =>
                {
                    b.Navigation("DoctorDetails");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.DoctorDetails", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorRatings");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.PatientDetails", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorRatings");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.PrescriptionDetails", b =>
                {
                    b.Navigation("PrescriptionDetailTimings");
                });

            modelBuilder.Entity("TapDoc_Mobile_App_Backend.Models.Users", b =>
                {
                    b.Navigation("DoctorDetails");

                    b.Navigation("PatientDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
